# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marty/encodertest/audioencoder

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marty/encodertest/audioencoder

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marty/encodertest/audioencoder/CMakeFiles /home/marty/encodertest/audioencoder//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marty/encodertest/audioencoder/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named encoder

# Build rule for target.
encoder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 encoder
.PHONY : encoder

# fast build rule for target.
encoder/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/build
.PHONY : encoder/fast

src/encoder.o: src/encoder.cpp.o
.PHONY : src/encoder.o

# target to build an object file
src/encoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/encoder.cpp.o
.PHONY : src/encoder.cpp.o

src/encoder.i: src/encoder.cpp.i
.PHONY : src/encoder.i

# target to preprocess a source file
src/encoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/encoder.cpp.i
.PHONY : src/encoder.cpp.i

src/encoder.s: src/encoder.cpp.s
.PHONY : src/encoder.s

# target to generate assembly for a file
src/encoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/encoder.cpp.s
.PHONY : src/encoder.cpp.s

src/fs.o: src/fs.cpp.o
.PHONY : src/fs.o

# target to build an object file
src/fs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/fs.cpp.o
.PHONY : src/fs.cpp.o

src/fs.i: src/fs.cpp.i
.PHONY : src/fs.i

# target to preprocess a source file
src/fs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/fs.cpp.i
.PHONY : src/fs.cpp.i

src/fs.s: src/fs.cpp.s
.PHONY : src/fs.s

# target to generate assembly for a file
src/fs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/fs.cpp.s
.PHONY : src/fs.cpp.s

src/lame_wrapper.o: src/lame_wrapper.cpp.o
.PHONY : src/lame_wrapper.o

# target to build an object file
src/lame_wrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/lame_wrapper.cpp.o
.PHONY : src/lame_wrapper.cpp.o

src/lame_wrapper.i: src/lame_wrapper.cpp.i
.PHONY : src/lame_wrapper.i

# target to preprocess a source file
src/lame_wrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/lame_wrapper.cpp.i
.PHONY : src/lame_wrapper.cpp.i

src/lame_wrapper.s: src/lame_wrapper.cpp.s
.PHONY : src/lame_wrapper.s

# target to generate assembly for a file
src/lame_wrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/lame_wrapper.cpp.s
.PHONY : src/lame_wrapper.cpp.s

src/log.o: src/log.cpp.o
.PHONY : src/log.o

# target to build an object file
src/log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/log.cpp.o
.PHONY : src/log.cpp.o

src/log.i: src/log.cpp.i
.PHONY : src/log.i

# target to preprocess a source file
src/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/log.cpp.i
.PHONY : src/log.cpp.i

src/log.s: src/log.cpp.s
.PHONY : src/log.s

# target to generate assembly for a file
src/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/log.cpp.s
.PHONY : src/log.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/wav.o: src/wav.cpp.o
.PHONY : src/wav.o

# target to build an object file
src/wav.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/wav.cpp.o
.PHONY : src/wav.cpp.o

src/wav.i: src/wav.cpp.i
.PHONY : src/wav.i

# target to preprocess a source file
src/wav.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/wav.cpp.i
.PHONY : src/wav.cpp.i

src/wav.s: src/wav.cpp.s
.PHONY : src/wav.s

# target to generate assembly for a file
src/wav.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encoder.dir/build.make CMakeFiles/encoder.dir/src/wav.cpp.s
.PHONY : src/wav.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... encoder"
	@echo "... src/encoder.o"
	@echo "... src/encoder.i"
	@echo "... src/encoder.s"
	@echo "... src/fs.o"
	@echo "... src/fs.i"
	@echo "... src/fs.s"
	@echo "... src/lame_wrapper.o"
	@echo "... src/lame_wrapper.i"
	@echo "... src/lame_wrapper.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/wav.o"
	@echo "... src/wav.i"
	@echo "... src/wav.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

